"""Execution Agent.

Runs the geometry task DAG in dependency order. Each task is generated by the
CAD Code Generation Agent, executed in the sandbox via the CAD adapter, and — on
failure — repaired by the Error Correction Agent and retried up to the task's
retry limit. Produces a :class:`GeometryResults` with per-task artifacts and
kernel topology metrics.
"""

from __future__ import annotations

from pathlib import Path
from typing import List, Optional

from ..adapters.base import CadToolAdapter
from ..llm.gateway import LLMGateway
from ..memory.session_memory import AgentSession
from ..types import (
    GeometryResults,
    GeometryTask,
    GeometryTaskDAG,
    PhysicsAugmentedIntent,
    TaskResult,
)
from .cad_code_generation_agent import CADCodeGenerationAgent
from .error_correction_agent import ErrorCorrectionAgent

_DEFAULT_FORMATS = ("step", "stl", "iges", "brep")


class ExecutionAgent:
    """Executes geometry tasks with a self-correction loop."""

    def __init__(
        self,
        adapter: CadToolAdapter,
        codegen: Optional[CADCodeGenerationAgent] = None,
        corrector: Optional[ErrorCorrectionAgent] = None,
        llm: Optional[LLMGateway] = None,
        formats=_DEFAULT_FORMATS,
    ):
        self.adapter = adapter
        self.codegen = codegen or CADCodeGenerationAgent(llm=llm)
        self.corrector = corrector or ErrorCorrectionAgent(llm=llm)
        self.formats = tuple(formats)

    def execute(
        self,
        dag: GeometryTaskDAG,
        augmented: PhysicsAugmentedIntent,
        out_dir: Path,
        session: AgentSession,
    ) -> GeometryResults:
        results = GeometryResults()
        out_dir = Path(out_dir)
        out_dir.mkdir(parents=True, exist_ok=True)

        for layer in dag.topological_sort():
            for task in layer:
                results.results.append(self._run_task(task, augmented, out_dir, session))
        return results

    def _run_task(
        self,
        task: GeometryTask,
        augmented: PhysicsAugmentedIntent,
        out_dir: Path,
        session: AgentSession,
    ) -> TaskResult:
        spec = self.codegen.generate(task, augmented)
        code = spec.script
        base = task.name.replace("/", "_")
        exports = {fmt: str(out_dir / f"{base}.{fmt}") for fmt in self.formats}

        last_error: Optional[str] = None
        for attempt in range(1, task.max_retries + 1):
            res = self.adapter.execute_script(code, exports, timeout_s=task.timeout_s)
            if res.success:
                session.log_task_success(task, attempt)
                # Surface derived params onto the result for the report/validation.
                return TaskResult(
                    task=task,
                    code=code,
                    success=True,
                    attempts=attempt,
                    artifacts=res.artifacts,
                    metrics={**res.metrics, "_derived": spec.derived},
                )
            last_error = res.error
            session.log_task_attempt(task, attempt, last_error)
            if attempt < task.max_retries:
                revised = self.corrector.correct(code, last_error or "", attempt)
                if revised:
                    code = revised

        return TaskResult(
            task=task,
            code=code,
            success=False,
            attempts=task.max_retries,
            error=last_error,
        )
