"""CFD results report builder (Markdown).

Assembles an engineer-readable report covering the ingested CEP, flow conditions,
mesh quality, solver/physics configuration, simulation status, extracted
quantities, and the validation verdict.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from ..types import (
    GeometryPreparationPackage,
    MeshPackage,
    SimulationResult,
    SolverConfigPackage,
)
from .results_validator import ResultsValidation


class CFDReportBuilder:
    """Builds the Markdown CFD report."""

    def build(
        self,
        prep: GeometryPreparationPackage,
        mesh: MeshPackage,
        config: SolverConfigPackage,
        result: SimulationResult,
        validation: Optional[ResultsValidation] = None,
    ) -> str:
        f = prep.flow_conditions
        L: list[str] = []
        L.append("# AeroForge AI — CFD Report")
        L.append("")
        L.append(f"**Component:** `{prep.manifest.component_type}`  ")
        L.append(f"**Domain:** {prep.domain_type.value}  ")
        L.append(
            f"**Solver:** {config.solver}  ·  **Turbulence:** {config.turbulence_model} "
            f"({config.wall_treatment})"
        )
        L.append("")

        L.append("## 1. Flow Conditions")
        L.append("")
        L.append("| Quantity | Value |")
        L.append("|---|---|")
        L.append(f"| Mach | {f.mach} ({f.regime.value}) |")
        L.append(f"| Velocity | {f.velocity_ms:.1f} m/s |")
        L.append(f"| Static T / p | {f.temperature_K:.1f} K / {f.pressure_pa:.0f} Pa |")
        L.append(f"| Density | {f.density:.4g} kg/m³ |")
        L.append(f"| Reynolds (L={f.characteristic_length_m:.3g} m) | {f.reynolds_number:.3e} |")
        L.append("")

        L.append("## 2. Mesh")
        L.append("")
        if mesh and mesh.success:
            L.append(f"- Mesher: **{mesh.mesher}** · format `{mesh.format}`")
            L.append(f"- Nodes: {mesh.n_nodes:,} · Cells: {mesh.n_cells:,}")
            if mesh.quality:
                L.append(
                    f"- Quality passed: **{mesh.quality.passed}** "
                    f"(skewness grade: {mesh.quality.grades.get('skewness','?')})"
                )
                for k, v in mesh.quality.metrics.items():
                    L.append(f"  - {k}: {v}")
                for w in mesh.quality.warnings:
                    L.append(f"  - ⚠️ {w}")
        else:
            L.append(f"- Meshing did not complete: {mesh.error if mesh else 'no mesh'}")
        L.append("")

        L.append("## 3. Solver Configuration")
        L.append("")
        L.append("Generated case files:")
        L.append("")
        for path in sorted(config.files):
            L.append(f"- `{path}`")
        L.append("")
        if config.notes:
            L.append("Configuration rationale:")
            L.append("")
            for n in config.notes:
                L.append(f"- {n}")
            L.append("")

        L.append("## 4. Simulation")
        L.append("")
        if result.success:
            L.append(f"- Converged: **{result.converged}** in {result.iterations} iterations")
            if result.final_residuals:
                L.append(
                    "- Final residuals: "
                    + ", ".join(f"{k}={v:.2e}" for k, v in result.final_residuals.items())
                )
            for k, v in result.quantities.items():
                L.append(f"- {k}: {v}")
        else:
            L.append(f"- Status: **case assembled, not solved**")
            if result.note:
                L.append(f"- {result.note}")
            if result.error:
                L.append(f"- Error: {result.error}")
        L.append("")

        if validation and validation.findings:
            L.append("## 5. Results Validation")
            L.append("")
            for fnd in validation.findings:
                mark = "✅" if fnd.passed else "⚠️"
                L.append(f"- {mark} {fnd.name}: {fnd.detail}")
            L.append("")

        L.append("---")
        L.append(
            "*Generated by AeroForge AI (CFD, Phase 2). Human review required before "
            "trusting results for design decisions.*"
        )
        L.append("")
        return "\n".join(L)

    def write(self, content: str, out_dir: Path) -> Path:
        path = Path(out_dir) / "cfd_report.md"
        path.write_text(content)
        return path
