"""OpenFOAM solver adapter — primary CFD backend.

Assembles a complete, runnable OpenFOAM case directory (``system/``, ``constant/``,
``0/`` plus the mesh) from a :class:`SolverConfigPackage` and a :class:`MeshPackage`.
When OpenFOAM is installed it converts the Gmsh mesh (``gmshToFoam``) and runs the
selected solver, streaming residuals; when it is not (as in this sandbox), it
still writes the full case and returns a clear "case assembled, solver not
installed" result. So the valuable, deterministic part — a ready-to-run case —
always works.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

from ..types import MeshPackage, SimulationResult, SolverConfigPackage
from .base import SolverAdapter


class OpenFOAMAdapter(SolverAdapter):
    name = "openfoam"

    def __init__(self, solver: str = "rhoSimpleFoam"):
        self.solver = solver

    def is_available(self) -> bool:
        return shutil.which(self.solver) is not None or shutil.which("foamRun") is not None

    def assemble_case(self, config: SolverConfigPackage, mesh: MeshPackage, case_dir: Path) -> Path:
        case_dir = Path(case_dir)
        for rel_path, content in config.files.items():
            target = case_dir / rel_path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content)

        # Place the mesh and record how to convert it to OpenFOAM polyMesh.
        if mesh and mesh.mesh_file and Path(mesh.mesh_file).exists():
            dest = case_dir / "mesh.msh"
            shutil.copy(mesh.mesh_file, dest)
            (case_dir / "Allrun.pre").write_text(
                "#!/bin/sh\n# Convert the Gmsh mesh to OpenFOAM polyMesh, then check it.\n"
                "gmshToFoam mesh.msh\ncheckMesh\n"
            )
        # A convenience Allrun that runs the selected solver.
        (case_dir / "Allrun").write_text(
            f"#!/bin/sh\n# Generated by AeroForge CFD.\nsh Allrun.pre\n{config.solver}\n"
        )
        (case_dir / "README.txt").write_text(
            "AeroForge-generated OpenFOAM case.\n\n"
            f"Solver: {config.solver}\nTurbulence: {config.turbulence_model} "
            f"({config.wall_treatment})\n\n"
            "To run (with OpenFOAM installed):\n"
            "  sh Allrun.pre   # gmshToFoam + checkMesh\n"
            f"  {config.solver}\n"
        )
        return case_dir

    def run(self, case_dir: Path, max_iterations: int = 2000) -> SimulationResult:
        case_dir = Path(case_dir)
        if not self.is_available():
            return SimulationResult(
                success=False,
                converged=False,
                iterations=0,
                case_dir=str(case_dir),
                note=(
                    f"Case fully assembled at {case_dir}, but the '{self.solver}' binary "
                    "is not installed here. Install OpenFOAM and run `sh Allrun`."
                ),
            )
        # OpenFOAM present: convert mesh and run the solver.
        try:
            subprocess.run(
                ["gmshToFoam", "mesh.msh"],
                cwd=case_dir,
                check=True,
                capture_output=True,
                text=True,
                timeout=600,
            )
            log = (case_dir / f"log.{self.solver}").open("w")
            proc = subprocess.run(
                [self.solver], cwd=case_dir, stdout=log, stderr=subprocess.STDOUT, timeout=7200
            )
            from ..monitoring.residual_tracker import ResidualTracker

            tracker = ResidualTracker()
            residuals, iters, converged = tracker.parse_log(case_dir / f"log.{self.solver}")
            return SimulationResult(
                success=proc.returncode == 0,
                converged=converged,
                iterations=iters,
                final_residuals=residuals,
                case_dir=str(case_dir),
                log_file=str(case_dir / f"log.{self.solver}"),
            )
        except Exception as exc:  # noqa: BLE001
            return SimulationResult(
                success=False, converged=False, iterations=0, case_dir=str(case_dir), error=str(exc)
            )
